Add Kubernetes TLS configuration documentation.
rabbitmq/rabbitmq-website pull request #1157
Opened 2021-03-17 15:57 UTC by MirahImage

Additional documentation in order to reduce user struggle configuring TLS for RabbitMQ clusters on Kubernetes.

2021-03-17 16:14 UTC, michaelklishin commented on site/kubernetes/operator/using-operator.md
> +configuring a RabbitMQ cluster to support <a href="#one-way-tls">TLS</a> or <a href="#mutual-tls">mutual TLS (mTLS)</a> encrypted traffic between clients and the cluter, as well as supporting <a href
Can we work in a link to our main TLS guide here, please?

2021-03-17 16:16 UTC, michaelklishin commented on site/kubernetes/operator/using-operator.md
> +or use a tool such as <a href="https://cert-manager.io/">Cert Manger</a> to generate a tls secret.
TLS secret

2021-03-17 16:16 UTC, michaelklishin commented on site/kubernetes/operator/using-operator.md
> +To enable TLS, create a Kubernetes secret containing the pem encoded server certificate `server.pem` and private key `server-key.pem`
PEM-encoded

2021-03-17 16:17 UTC, michaelklishin commented on site/kubernetes/operator/using-operator.md
> +In order to enforce client verification, RabbitMQ must be configured to reject clients that do not present certificates. This can be done by enabling `ssl.options.fail_if_no_peer_cert` in the additio
`ssl.options` should be `ssl_options`. We should also link to [this TLS guide section](https://www.rabbitmq.com/ssl.html#peer-verification), most users have a fairly vague idea of what peer verification really is.

2021-03-17 16:18 UTC, michaelklishin requested changes
This is a good start but could benefit from more linking and also has a few typos. We can link to this section from the main TLS guide, e.g. "for enabling TLS for client connections on Kubernetes, see this section in the Kubernetes Operator guide"

2021-03-18 10:18 UTC, MirahImage commented
I have made the requested changes and added a link from the TLS page to this documentation.

2021-03-22 18:00 UTC, michaelklishin commented on site/kubernetes/operator/using-operator.md
> +configuring a RabbitMQ cluster to support <a href="#one-way-tls">TLS</a> or <a href="#mutual-tls">mutual TLS (mTLS)</a> encrypted traffic between clients and the cluter, as well as supporting <a href
Sounds good

2021-03-31 20:37 UTC, michaelklishin approved these changes

2021-03-31 20:37 UTC, merged