add amqp-client-python to devtools.md
rabbitmq/rabbitmq-website pull request #1773
Opened 2023-12-04 16:02 UTC by berrytern

It is a client library with high abstraction level with auto reconnection,  supported by [NUTES](https://nutes.uepb.edu.br/) and developed as an open source project.

2023-12-04 20:12 UTC, lukebakken requested changes

2023-12-05 14:00 UTC, lukebakken approved these changes

2023-12-05 14:42 UTC, michaelklishin commented
@pivotal-cla this is an obvious fix

2023-12-05 14:42 UTC, pivotal-cla commented
@berrytern This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

2023-12-05 14:43 UTC, merged

2023-12-05 14:53 UTC, michaelklishin commented
I wish this project was named differently, "amqp client Python" is too generic. Now that AMQP 0-9-1 and AMQP 1.0 Python clients have been around for some 16 years, gooling for "amqp client python" will land you anywhere but this project.