DO NOT MERGE YET Stream Tutorial 2
rabbitmq/rabbitmq-website pull request #1952
Opened 2024-06-17 13:54 UTC by acogoluegnes

2024-06-17 15:38 UTC, acogoluegnes commented on tutorials/tutorial-two-java-stream.md
> +We'll use [the stream Java client](/tutorials/tutorial-one-java-stream#using-the-java-stream-client).
Sounds good, I'll update the tutorial for consistency's sake.

2024-06-20 16:02 UTC, lukebakken reviewed
What do you think about using the word "marker" instead of "poison" to indicate stopping the consumer? The only reason I bring it up is that "poison" is used in our docs to describe messages that cause consumers to throw exceptions or otherwise have errors when processing.

I can make the change, too.

2024-06-20 19:58 UTC, lukebakken approved these changes
I replaced `poison` with `marker` 😇 Tutorial code updated here as well - https://github.com/rabbitmq/rabbitmq-tutorials/pull/421

2024-06-28 10:05 UTC, binarin reviewed
I've followed the tutorial from the start to the end, everyting is clear and works exactly as it says. It's just a bit bumpy if you want to follow it from scratch, as there is no easy way for getting all the boilerplate ready, and some pieces of code are omitted from the text of the tutorial.

2024-07-03 13:47 UTC, acogoluegnes commented on tutorials/tutorial-two-java-stream.md
> +Make sure to follow [the setup steps](/tutorials/tutorial-one-java-stream#setup) from the first tutorial.
I don't think it's manageable: we have dozens of tutorials, it's very unlikely we manage to maintain all of them with the start and end states.

2024-07-03 15:23 UTC, acogoluegnes commented on tutorials/tutorial-two-java-stream.md
> +boolean completed = confirmedLatch.await(60, TimeUnit.SECONDS);
That's right, we should mention in the first tutorial that one should wait for the publish confirm, I'll open a new PR for this.

2024-07-04 15:35 UTC, acogoluegnes commented on tutorials/tutorial-two-java-stream.md
> +boolean completed = confirmedLatch.await(60, TimeUnit.SECONDS);
https://github.com/rabbitmq/rabbitmq-website/pull/1963

2024-07-08 13:58 UTC, Gsantomaggio requested changes

2024-07-08 13:58 UTC, Gsantomaggio commented on tutorials/tutorial-two-go-stream.md
> +			for _, _ = range confirmed {
Here, we count the confirmations,  but:
```golang
	for _, msg := range confirmed {
		 if msg.IsConfirmed() {
		
```

With `.IsConfirmed()`, you are sure that the server has confirmed the message. 

not sure we have to deal with `.IsConfirmed()` here or maybe directly to another tutorial.

2024-07-08 13:58 UTC, Gsantomaggio commented on tutorials/tutorial-two-go-stream.md
> +        consumerContext.Consumer.Close()
I usually suggest closing the consumer outside the message handler.

2024-07-08 13:58 UTC, Gsantomaggio commented on tutorials/tutorial-two-go-stream.md
> +
Here you can declare the `consumer, err := .....` then:

```golang
_ = <-ch
consumer.close()
```

2024-07-08 14:18 UTC, Gsantomaggio commented on tutorials/tutorial-two-go-stream.md
> +        consumerContext.Consumer.Close()
done via: https://github.com/rabbitmq/rabbitmq-website/pull/1952/commits/81ddb9e4699a7701c026571ba99fc11e091c6837

2024-08-02 07:32 UTC, merged